### PR TITLE
chore: Hero text for the hero section (WEB-10)

### PR DESCRIPTION
**Pull request by JVPH**

### CODE REVIEW

**Comment by TheDThompsonDev** [comment]
Merge conflicts. Please rebase and fix.

**Comment by TheDThompsonDev** [comment]
There are merge conflicts on this branch. can you please rebase so we can add this one to the codebase. Let me know if you have any questions.

**Comment by JVPH** [comment]
Sorry, just saw this. Fixing it now!

**Comment by joshuaow91** [comment]
> Sorry, just saw this. Fixing it now!

try running npx prettier --write .

that should pass the prettier check

**Comment by JVPH** [comment]
> > Sorry, just saw this. Fixing it now!
> 
> try running npx prettier --write .
> 
> that should pass the prettier check

Thanks! All checks passed now!

**Comment by TheDThompsonDev** [comment]
LGTM!

**Pull request merged**
