### PR TITLE
chore: Fix layout with cards on home page

### PR DESCRIPTION
**Pull request by climaxmba**
# chore: Fix layout with cards on home page #108

### CODE REVIEW

**Comment by climaxmba** [comment]
# 1024px:
image

# 769px:
image

**Comment by GetBlackBoxSolutions** [comment]
I apologize but there was a mix up with this ticket and I was talking to another developer prior to me creating the ticket. I appreciate the timely manner but I'm going to close this PR out. I have another task if you want to contribute just let me know. Also are you on Discord?

**Comment by climaxmba** [comment]
> I apologize but there was a mix up with this ticket and I was talking to another developer prior to me creating the ticket. I appreciate the timely manner but I'm going to close this PR out. I have another task if you want to contribute just let me know. Also are you on Discord?

Yeah I'm on Discord, I'm also on the DSD and "Coming your Code" server.

**Comment by climaxmba** [comment]
Hey by the way, while working on this I noticed that some tests where failing.

**Pull request closed without merging**
